#
# CORE CONFIGURATION OPTIONS
#
readconfig                1
writeconfig               0

#
# SCRIPTING OPTIONS
#
plugins                   1

#
# CORE PERFORMANCE OPTIONS
#
lowlatency                1

#
# CORE VECTOR OPTIONS
#
beam_width_min            2.0
beam_width_max            5.0
beam_dot_size             2.0
beam_intensity_weight     0.75
flicker                   0.15
