#
# CORE VECTOR OPTIONS
#
beam_width_min            1.00
beam_width_max            4.00
beam_intensity_weight     0.75
flicker                   0.15

#
# VECTOR POST-PROCESSING OPTIONS
#
vector_beam_smooth        0.0
vector_length_scale       0.5
vector_length_ratio       0.5

