#!/usr/bin/env zsh

zparseopts -D -F - -debug=zdebug || exit 1

PATH=${ZSH_SCRIPT:h}/bin:$PATH
RACONFIG=( ~/Library/Application\ Support/RetroArch/config/retroarch.cfg )

function dprint {
  if (( ${#zdebug} )); then
    local flag cn zl l=-
    zparseopts -D -F - l=zl {ok,no,c0,c1,c2,c3,c4,c5,c6,c7}=flag || exit 1
    (( ${#zl} )) && l=' '
    cn=${${flag#-c}:-0}
    case ${flag[-1]} in
      -no) printf "✗ \e[0;31m%s\e[0m\n" $@ ;;
      -ok) printf "✓ \e[0;32m%s\e[0m\n" $@ ;;
        *) printf "$l \e[0;3${cn}m%s\e[0m\n" $@ ;;
    esac
  fi
}

function cfg_dir {
  printf %s "${$( sed -En "s/^$1 = \"(.+)\"/\1/p" $RACONFIG )/#\~\//$HOME/}"
}

function set_hz {
  local serial=`rascreen --serial` retry=0 hz

  while [[ -z $serial ]]; do
    # rascreen called to early, so wait a second.
    dprint -no "rascreen not ready, waiting..."
    sleep 1
    serial=`rascreen --serial`
    if (( retry++ && retry >= 5 )); then
      dprint -no "rascreen is not responding."
      exit 1
    fi
  done

  print "Requested: ${1}Hz"

  if ! type screen-$serial &>/dev/null; then
    print "Screen not recognized (serial: $serial)." >&2
  elif hz=`screen-$serial $1`; then
    # Don't block. To be cleaned up later when unloading the running core.
    rascreen --set-hz $hz &
    RASCREEN_PIDS+=$!
  else
    print "Unhandled refresh rate (serial: $serial, requested: ${1}hz)." >&2
  fi
}

function watch_exit {
  while pgrep -x RetroArch &>/dev/null; do
    sleep 2
  done
  dprint -ok "Stop: watch_exit"
  # The log gets truncated when RetroArch launches causing confusion with tail.
  # It misses a few lines and places the script in an unknown state. Move it with
  # a *-last.log suffix so it creates a new one on next launch.
  # `tail -F` in the main loop will follow the new log file.
  local log_dir=`cfg_dir log_dir`
  if [[ -f $log_dir/retroarch.log ]]; then
    mv -f $log_dir/retroarch.log $log_dir/retroarch-last.log
  fi
}

typeset -a av_search=(
  '([0-9]+x[0-9]+)'
  'Aspect: ([0-9]\.[0-9]+)'
  'FPS: ([0-9]+\.[0-9]+)'
  'Sample rate: ([0-9]+\.[0-9]+)'
)

# Required logging options for the script to function.
typeset -A log_options=(
  frontend_log_level    1
  log_to_file           true
  log_to_file_timestamp false
  log_verbosity         true
)
for key value in ${(@kv)log_options}; do
  sed -i '' "s/^$key = .*/$key = \"$value\"/" $RACONFIG
  if ! grep -q "^$key = \"$value\"" $RACONFIG; then
    print -- "$key = \"$value\"" >> $RACONFIG
  fi
done

# Log parsing loop:
# - content loading
# - core loading                  -> set loading context.
#   - get refresh rate
#   - start synchronous audio     -> set running context.
#     - set refresh rate!
#     - get refresh rate          1. running context loop.
#     - start synchronous audio   2. running context loop.
#       - set refresh rate!       3. running context loop.
# - unloading core or quit        -> set closing context.
#   - release refresh rates!

tail -Fn-1 "`cfg_dir log_dir`/retroarch.log" | while read line; do

  # Content Loading:
  # - When run from the menu system, loads as "[INFO] [Core] Using content:"
  # - When run from the cli, loads as "[INFO] [Content] Loading content file:"
  #   if it does at all. It depends on the media type.
  # - Some cores will log both forms when run from the menu.
  # [[ $gpath:t =~ "(.*\.[[:alnum:]]{2,3})\#(.*)\.[[:alnum:]]{2,4}$" ]]
  if [[ $line =~ '\[Core\] Using content: "(.+)"' ]]; then
    dprint -ok "Content Loading"
    content_path=${match[1]}
    print "loading: ${content_path/#$HOME/~}"

  # Core Loading:
  elif [[ $line =~ '\[Core\] Loading dynamic libretro core from: ".+\/(.+)\.dylib"' ]]; then
    core=$( sed -En 's/^corename = "(.+)"/\1/p' "`cfg_dir libretro_info_path`/${match[1]}.info" )
    dprint -ok "Core Loading: $core"
    loading=1
    running=0
    closing=0
    RASCREEN_PIDS=()
  fi

  # Loading Context:
  if (( loading )); then

    # Get Refresh Rate:
    if [[ $line =~ "\[Core\] Geometry: ${(j:, :)av_search}" ]]; then
      dprint "AV Information"
      dprint -l dimensions:${match[1]} aspect-ratio:${match[2]} refresh-rate:${match[3]}Hz sample-rate:${match[4]}Hz
      # Emulated machine's refresh rate.
      emuhz=${match[3]}
      srate=${match[4]}

    elif [[ $line =~ '\[Audio\] Set audio input rate to: ([0-9]+\.[0-9]+)' ]]; then
      arate=${match[1]}
      if [[ -n $srate ]]; then
        printf 'Dynamic Rate Control: sample rate %sHz, deviation %+.4f%%.\n' \
          $arate $(( (arate - srate) / srate * 100 ))
      fi

    # Warning! `video_refresh_rate` is not properly set.
    elif [[ $line =~ '\[Video\] Timings deviate too much.+= ([0-9]+\.[0-9]+).+ = ([0-9]+\.[0-9]+)' ]]; then
      printf 'Dynamic Rate Control: requested rate (%sHz) deviates too far from setting (%sHz).\n' \
        ${match[2]} ${match[1]}

    # Start Synchronous Audio -> Set Refresh Rate & Running Context:
    # When the audio system is ready, the game is ready. Long delays for heavier
    # cores is common.
    elif [[ $line =~ '\[Audio\] Started synchronous audio driver.' ]]; then
      dprint -ok "Start Synchronous Audio - Emulation Started"
      set_hz $emuhz
      loading=0
      running=1
      closing=0
    fi

  # Running Context:
  elif (( running )); then

    # Get Refresh Rate:
    # Mid-run refresh rate changes. Mainly applies to MAME emulation.
    if [[ $line =~ "\[Environ\] SET_SYSTEM_AV_INFO: ${(j:, :)av_search}" ]]; then
      if [[ -n $emuhz && $emuhz != ${match[3]} ]]; then
        dprint -c3 "AV Information - Update"
        dprint -l dimensions:${match[1]} aspect-ratio:${match[2]} refresh-rate:${match[3]}Hz sample-rate:${match[4]}Hz
        emuhz=${match[3]}
        srate=${match[4]}
      fi

    elif [[ $line =~ '\[Audio\] Set audio input rate to: ([0-9]+\.[0-9]+)' ]]; then
      # MAME can get noisy with some emulated machines, e.g., sega/stv.cpp->cotton2.
      # Surpress repeated attempts that doesn't change anything at all.
      if [[ -n $srate && $arate != ${match[1]} ]]; then
        arate=${match[1]}
        printf 'Dynamic Rate Control: sample rate %sHz, deviation %+.4f%%.\n' \
          $arate $(( (arate - srate) / srate * 100 ))
        switch=1
      else
        switch=0
      fi

    # Warning! `video_refresh_rate` is not properly set or the core has not settled
    # to the correct refresh rate. This can happen with some systems in MAME, e.g.,
    # sega/stv.cpp->cotton2 switches refresh rates multiple times while booting.
    elif [[ $line =~ '\[Video\] Timings deviate too much.+= ([0-9]+\.[0-9]+).+ = ([0-9]+\.[0-9]+)' ]]; then
      if [[ $requestedhz != ${match[2]} ]]; then
        requestedhz=${match[2]}
        printf 'Dynamic Rate Control: requested rate (%sHz) deviates too far from setting (%sHz).\n' \
          ${match[2]} ${match[1]}
      fi

    # Set Refresh Rate:
    elif [[ $line =~ '\[Audio\] Started synchronous audio driver.' ]]; then
      if (( switch )); then
        dprint -ok "Switch Refresh Rate"
        set_hz $emuhz
      fi

    # Unload Core or Close -> Release Refresh Rates:
    elif [[ $line =~ "(\[Core\] Unloading core...|\[NS\] stopping draw observer)" ]]; then
      if [[ -n $core ]]; then
        dprint -ok "Unloading Core: $core"
      fi
      loading=0
      running=0
      closing=1
    fi
  fi

  # Closing Context:
  if (( closing )); then
    for pid in $RASCREEN_PIDS; do
      # kill rascreen from this load cycle.
      if [[ `ps -p $pid -o comm= 2>/dev/null` == rascreen ]]; then
        dprint "kill $pid: rascreen"
        kill $pid
        print "refresh rate released."
      fi
    done
  fi

  # A singleton to detect when RetroArch has exited.
  if ! kill -0 $watch_exit_id 2>/dev/null; then
    dprint -ok "Start: watch_exit"
    watch_exit &
    watch_exit_id=$!
    # Trap and kill when the script exits or is interrupted.
    trap 'kill $watch_exit_id 2>/dev/null && dprint -no "kill $!: watch_exit"' INT TERM EXIT
  fi
done
