#!/usr/bin/env zsh

if [[ -f $1:h/$1:t:r.lck ]]
then
  echo "Core is locked."
  exit 0
fi

arch=( `lipo -archs $1` )
dylib=$1:t

url=https://buildbot.libretro.com/nightly/apple/osx/$arch/latest/$dylib.zip

if remote_header=`curl --silent --head --fail $url`
then
  if [[ $remote_header =~ "last-modified: (.+GMT)" ]]
  then
    # Standard HTTP format: "Thu, 09 Jul 2026 14:32:22 GMT"
    # The format string must match: Day, Date Month Year Time Timezone
    if [[ `stat -f %m $1` -gt `date -j -f "%a, %d %b %Y %H:%M:%S %Z" "$match[1]" "+%s"` ]]
    then
      echo "Core is already up to date. [$match[1]]"
      exit 0
    fi
  else
    echo "Failed to determine remote date." >&2
    exit 1
  fi

  sleep 2
  tmpdir=`mktemp -d`
  if curl -Lo $tmpdir/$dylib.zip $url; then
    if unzip $tmpdir/$dylib.zip -d $tmpdir
    then
      touch $tmpdir/$dylib
      mv -vf $tmpdir/$dylib $1
    else
      echo "Failed to extract core." >&2
      exit 1
    fi
  else
    echo "Failed to download core." >&2
    exit 1
  fi
  rm -rf $tmpdir
else
  echo "Remote file does not exist. [$url]" >&2
  exit 1
fi
