#!/usr/bin/env zsh

if [[ -f $1:r.lck ]]
then
  echo "core is locked."
  exit 0
fi

# host_arch: arm64 or x86_64
# core_arch: arm64 and/or x86_64
# arch: hardware aligned core arch with fallsback. arm64 or x86_64
host_arch=( `uname -m` )
core_arch=( `lipo -archs $1` )
arch=${${core_arch:*host_arch}:-$core_arch}

index_cache=$TMPDIR/core-update-index-$arch.txt
# index_cache updated when older than 10 minutes.
if [[ ! -f $index_cache || $(( `date +%s` - `date -r $index_cache +%s` )) -gt 600 ]]
then
  if ! curl -so $index_cache https://buildbot.libretro.com/nightly/apple/osx/$arch/latest/.index-extended
  then
    echo "failed to fetch remote index." >&2
    exit 1
  fi
fi

dylib=$1:t
name=${${dylib:t}%_libretro.dylib}

if [[ `cat $index_cache` =~ "([0-9a-z]+) $dylib.zip" ]]
then
  if [[ `crc32 $1` == ${match[1]} ]]
  then
    echo "$name is up to date."
    exit 0
  fi
else
  echo "failed to determine remote revision for $name." >&2
  exit 1
fi

tmpdir=`mktemp -d`
trap 'rm -rf $tmpdir' INT TERM EXIT

echo "downloading $name core..."
if ! curl -#Lo $tmpdir/$dylib.zip https://buildbot.libretro.com/nightly/apple/osx/$arch/latest/$dylib.zip
then
  echo "download failed." >&2
  exit 1
fi

if unzip -q $tmpdir/$dylib.zip -d $tmpdir
then
  mv -f $tmpdir/$dylib $1
else
  echo "failed to extract core." >&2
  exit 1
fi
