#!/usr/bin/env zsh

if [[ -f $1:h/$1:t:r.lck ]]
then
  echo "core is locked."
  exit 0
fi

# host_arch: arm64 or x86_64
# core_arch: arm64 and/or x86_64
# arch: hardware aligned core arch with fallsback. arm64 or x86_64
host_arch=( `uname -m` )
core_arch=( `lipo -archs $1` )
arch=${${core_arch:*host_arch}:-$core_arch}
dylib=$1:t

url=https://buildbot.libretro.com/nightly/apple/osx/$arch/latest/$dylib.zip

if ! remote_header=`curl --silent --head --fail $url`
then
  echo "remote file does not exist. [$url]" >&2
  exit 1
fi

etag=$1:h/.etags/$1:t:r-$arch.txt
mkdir -p $etag:h

if [[ $remote_header =~ "etag: \"([0-9]+)\"" ]]
then
  remote_etag=${match[1]}
  if [[ -f $etag && `cat $etag` == $remote_etag ]]
  then
    echo "core is up to date."
    exit 0
  fi
else
  echo "failed to determine remote revision." >&2
  exit 1
fi

tmpdir=`mktemp -d`
trap 'rm -rf $tmpdir' INT TERM EXIT

if ! curl --progress-bar --location --output $tmpdir/$dylib.zip $url
then
  echo "failed to download core." >&2
  exit 1
fi

if unzip -q $tmpdir/$dylib.zip -d $tmpdir
then
  mv -f $tmpdir/$dylib $1
  echo $remote_etag > $etag
else
  echo "failed to extract core." >&2
  exit 1
fi
