#!/usr/bin/env zsh
#
# MAME config overrides:
# - Save state related settings disabled when a machine doesn't support it.
# - TATE mode sets `video_scale_integer_axis` to X.
#
PATH=$( dirname `realpath $0` ):$PATH

if ! mameinfo --init-path $1
then
  echo "Failed to initialize." >&2
  exit 1
fi
if [[ $( raconfig --get config_save_minimal ) == true ]]
then
  echo "Incompatible with 'config_save_minimal'." >&2
  exit 1
fi

scandir=$1
cfgdir=$( raconfig --get rgui_config_directory )/MAME

typeset -a savestate_related_supported savestate_related_unsupported
# Prefixed `-keys` to disable only. Will not be restored to defaults.
for skey in menu_show_latency \
            menu_show_rewind \
           -preemptive_frames_enable \
            quick_menu_show_replay \
            quick_menu_show_save_load_state \
            quick_menu_show_savestate_submenu \
            quick_menu_show_undo_save_load_state \
           -run_ahead_enabled \
            savestate_auto_load \
            savestate_auto_save
do
  # To be used to reset when it's supported.
  if [[ $skey[1] != - ]]
  then savestate_related_supported+=${skey#-}=$( raconfig --get ${skey#-} $cfgdir/MAME.cfg )
  fi
  # And disabled when it's not.
  savestate_related_unsupported+=${skey#-}=false
done

# TATE Integer Axis: X
tate_ia=4
typeset -A map_sia=(
  0 'Scale Integer Axis Y'
  1 'Scale Integer Axis Y+X'
  2 'Scale Integer Axis Y+X.5'
  3 'Scale Integer Axis Y.5+X.5'
  4 'Scale Integer Axis X'
  5 'Scale Integer Axis X.5'
)

while read -r line
do
  typeset -A processed
  while read -r key value
  do typeset $key=$value
  done < <( jq -r 'to_entries[] | "\(.key) \(.value)"' <<< $line )

  scpp=-${${sourcefile:r}//\//-}
  if [[ $rotate == (90|270) ]]
  then scpp+=\~tate
  fi

  if (( $processed[$scpp] ))
  then continue
  fi

  changes=0
  keyvalues="savestate_related_${savestate}"
  for kv in ${(P)keyvalues}
  do
    if [[ $( raconfig --get ${kv%=*} $cfgdir/$scpp.cfg ) != ${kv#*=} ]]
    then
      raconfig --override $kv $cfgdir/$scpp.cfg &
      changes=1
    fi
  done
  if (( changes ))
  then printf '%s.cfg: Save State %s. Related settings were updated.\n' $scpp $savestate
  fi

  if [[ $rotate == (90|270) ]]
  then
    if [[ $(
      raconfig --get video_scale_integer_axis $cfgdir/$scpp.cfg
    ) != $tate_ia ]]
    then
      raconfig --override video_scale_integer_axis=$tate_ia $cfgdir/$scpp.cfg &
      printf '%s.cfg: %s\n' $scpp ${map_sia[$tate_ia]}
    fi
  fi
  processed[$scpp]=1

done < <( mameinfo -cr 'select( .isbios != "yes" and .isdevice != "yes" ) |
        { name:.name,
          sourcefile:.sourcefile,
          savestate:.driver.savestate,
          rotate:.display[0].rotate }' $scandir/*.(7z|zip) )
