#!/usr/bin/env zsh
#
# Hardlinks MAME roms to the .sorted directory based on mameinfo .sourcefile.
# This enables directory based cfg overrides, core options and controller
# remapping. A set of games for a given source are likely to share settings.
#
PATH=$( dirname `realpath $0` ):$PATH
scandir=$1

if ! mameinfo --init-path $scandir
then
  echo "Failed to initialize." >&2
  return 1
fi

if [[ ! -d $scandir/.sorted ]]
then
  mkdir $scandir/.sorted
  # exclude from time machine backups.
  tmutil addexclusion $scandir/.sorted
fi
rm -rf $scandir/.sorted/*(N)

if [[ -n ${commands[tag]} ]]
then
  # Tagged files to ignore
  ignore=(
    ${${(f)"$( tag -m Ignore $scandir/*.(7z|zip) )"}:t:r}
  )
fi

counter=0
while read -r line
do
  # Modulus matches the number of items queried in mameinfo. @see bottom of loop.
  case $(( ++counter % 6 )) in
    1)  name=$line ;;
    2)  isbios=$line ;;
    3)  isdevice=$line ;;
    4)  scpp=-${${line:r}//\//-} ;;
    5)  [[ $line == (90|270) ]] && scpp+=\~tate ;;
    0)
        # Ignore bios, devices and tagged for ignore.
        [[ yes == ($isbios|$isdevice) || -n ${ignore[(r)$name]} ]] && continue
        sdir=$scandir/.sorted/$scpp
        [[ -d $sdir ]] || mkdir -p $sdir
        ln $scandir/$name.zip $sdir/$name.zip
        # highlight containing folder.
        printf "%s\n\e[0;34m%s\e[0;37m/\e[0m%s\n" $line $scpp $name.zip
      ;;
  esac
done < <( mameinfo -r ' .name,
                        .isbios,
                        .isdevice,
                        .sourcefile,
                        .display[0].rotate,
                        .description ' $scandir/*.zip )
