#!/usr/bin/env zsh
#
# Generates database/[scan directory].xml specific to the roms directory.
# For use with playlists to get proper names.
#
# requires standalone mame
#

romsdir=${1:a}
basedir=~/Library/Application\ Support/RetroArch
mamexml=$basedir/database/${romsdir:t}.xml
append_dir=$basedir/database/${romsdir:t}-append

all_names=( $romsdir/*.(7z|zip)(N:t:r) )
# Get names to append, specific to the rom directory being scanned.
append_all=( $append_dir/*.xml(N:t:r) )
append_names=( ${all_names:*append_all} )

# Filter out appended names. It will be processed later.
if [[ -n ${all_names:|append_names} ]]
then
  mame -listxml ${all_names:|append_names} > $mamexml
fi

if [[ -n $append_names ]]
then
  echo "Appending ${(j/,/)append_names}..."
  {
    # print main xml file, but omit closing </mame> tag.
    sed '/<\/mame>/d' $mamexml

    for name in $append_names
    do
      # print `/mame/machine` and omits the following:
      # 1. xml declaration line
      # 2. doctype & specs
      # 3. opening <mame> line
      # 4. closing </mame> line
      sed '/<?xml/d;/<!/d;/]>/d;/<mame/d;/<\/mame>/d' $append_dir/$name.xml
    done

    # print the closing tag.
    echo "</mame>"
  } > $mamexml.tmp && mv -f $mamexml.tmp $mamexml
fi
