#!/usr/bin/env zsh
#
# Hardlinks MAME roms to the .sorted directory based on `mame -sourcelist`
# This enables directory based cfg overrides, core options and controller
# remapping. A set of games for a given source are likely to share settings.
#

if ! type mame &>/dev/null
then
  echo "mame required" >&2
  return 1
fi

local scandir=~/Games/Emulation/Arcade
local sortdir=$scandir/.sorted

if [[ ! -d $sortdir ]]
then
  mkdir $sortdir
  # exclude from time machine backups.
  tmutil addexclusion $sortdir
fi

rm -rf $sortdir/*(N)

typeset -A missing=(
  akatana cave/cv1k.cpp
  ddpsdoj cave/cv1k.cpp
)
typeset -aU names=(
  $scandir/*.(7z|zip)(N:t:r)
)

if (( ${#names} ))
then
  sources=( ${(f)"$( mame -listsource $names 2>/dev/null )"} )
  for key in ${(k)missing}; [[ -n ${names[(r)$key]} ]] && {
    sources+="$key $missing[$key]"
  }
  for listsource in $sources
  do
    set -- ${(s: :)listsource}

    name=$1
    scpp=-${${2:r}/\//-}
    source=$scandir/$name.zip
    target=$sortdir/$scpp/$name.zip

    # optional tags to ignore.
    if type tag &>/dev/null && tag -Nlg $source | grep -Eq "^(Ignore|Device|BIOS)$"
    then
      continue
    fi

    test -d $target:h || mkdir -p $target:h
    ln $source $target
    printf "\e[0;34m%s\e[0;37m/\e[0m%s\n" $scpp $name.zip
  done
fi
