#!/usr/bin/env zsh
#
# Hardlinks MAME roms to the .sorted directory based on the 'sourcefile'
# key within `mame -listxml`. This enables directory based cfg overrides,
# core options and controller remapping. A group of MAME "machines" or
# games for a given source are more likely to share specific settings.
#

PATH=$( dirname `realpath $0` ):$PATH

local scandir=~/Games/Emulation/Arcade
local sortdir=$scandir/.sorted

if ! mameinfo --init-dir $scandir
then
  echo "Failed to initialize." >&2
  return 1
fi

if [[ ! -d $sortdir ]]
then
  mkdir $sortdir
  # exclude from time machine backups.
  tmutil addexclusion $sortdir
fi

# managing dependencies is too complicated, so wipe it on each run.
rm -rf $sortdir/*(N)

s.print() {
  local c1=00
  case ${1[1]} in
    +)  c1=32 ;;
    -)  c1=33 ;;
  esac
  printf "\e[1;30m%s\e[0m\n  \e[0;${c1}m%s\e[0m%s\n" "$(
    mameinfo -r .description -g $scandir/$2:t
  )" "$1:" "${2#$scandir/}"
}

for rom in $scandir/*.(7z|zip)(N)
do
  if ! mameinfo --exists $rom
  then
    print "unrecognized '$rom'" >&2
    continue
  fi

  if type tag &>/dev/null && tag -Nlg $rom | grep -q "^Ignore$"
  then
    continue
  fi

	read -d '' sourcefile isbios isdevice < <(
    mameinfo -r .sourcefile,.isbios,.isdevice -g $rom
  )
  case yes in
    # skip bios and devices.
    $isbios|$isdevice) continue ;;
  esac

  name=$rom:t:r
  extension=$rom:e
  sourcefolder=$rom:h
  targetfolder=$sortdir/-${${sourcefile:r}/\//-}


  source=$rom
  target=$targetfolder/$rom:t

  mkdir -p $target:h
  ln -f $source $target
  s.print +linked $target

  continue
