#!/usr/bin/env zsh

zparseopts -D -F - -all=zall -force=zforce -update=zupdate || return 1

configs=( Release Debug )
if [[ -n ${@:|configs} ]]
then
  print "Unknown build configuration: ${@:|configs}" >&2
  return 1
fi
builds=( ${@:-Release} )
if (( ${#zall} ))
then
  builds=( $configs )
fi
print "Building for the following: ${(j:, :)builds}"

base_dir=~/Projects/emulation/libretro
repos=(
  retroarch-apple-deps
  libretro-super/retroarch
)
updates=0
stashed=()

if (( ${#zupdate} ))
then
  for repo in $repos
  do
    cd $base_dir/$repo || return 1
    print "Updating repo: $repo"

    if ! git fetch
    then
      print "fetch failed." >&2
      return 1
    elif (( $( git rev-list --count HEAD..@{u} ) > 0 ))
    then
      let updates++
      if git stash | grep -q '^Saved working directory'
      then
        stashed=1
      else
        stashed=0
      fi
      # A pull *merge commits* by default but there's no difference with
      # a rebase when there are no locally made commits. A rebase on the
      # other hand allows local commits by replaying them back on top of
      # the upstream commits. It is more flexible so use rebase.
      if ! git rebase
      then
        print "rebase failed." >&2
        return 1
      fi
      if [[ -n $( git submodule status ) ]] &&
        ! git submodule update --init --recursive
      then
        print "submodule update failed." >&2
        return 1
      fi
      if (( stashed ))
      then
        git stash pop || return 1
      fi
    fi
  done
fi

if (( updates > 0 || ${#zforce} ))
then
else
  print "Nothing to update."
  return 0
fi

project=pkg/apple/RetroArch_Metal.xcodeproj
xcodebuild clean -project $project

for config in $builds
do
  # Sharing Metal caches invalidates it when switching between arches. It
  # causes significant startup delays when launching LRPS2 under x86_64.
  # Then it happens again when launching Dolphin under arm64. Keep each
  # arch build seperated with a unique bundle id which Metal uses for
  # caching under: /private/var/folders/yt/hjxkrfvs1mz2nsb2_dtfwftw0000gn/C
  for arch in arm64 x86_64
  do
    # - self-sign stash required for local build.
    # - stach specific to arch. x86_64 uses bundle id of: com.libretro.dist.RetroArchX86
    if ! git stash apply refs/$( git stash list | sed -nE "s/^(.+):.+: local build ${arch}$/\1/p" )
    then
      print "stash apply ::local build $arch:: failed" >&2
      return 1
    fi

    xcodebuild -target RetroArch -configuration $config ARCHS=$arch -project $project
    ret=$?
    git restore $project/project.pbxproj
    if (( ret ))
    then
      print "xcode build failed for '-configuration $config ARCHS=$arch'." >&2
      return 1
    fi

    # Copy to the /Application directory only for Release builds.
    if [[ $config == Release ]]
    then
      mkdir -p /Applications/RetroArch
      if [[ $arch == x86_64 ]]
      then
        rm -rf /Applications/RetroArch/RetroArchX86.app
        mv pkg/apple/build/Release/RetroArch.app /Applications/RetroArch/RetroArchX86.app
      else
        rm -rf /Applications/RetroArch/RetroArch.app
        mv pkg/apple/build/Release/RetroArch.app /Applications/RetroArch
      fi
    fi
  done
done
print "Build completed for ${(j:, :)builds}."
