#!/usr/bin/env zsh

zparseopts -D -E - -x86_64=zX86 -build=zbuild || return 1

if (( ${#zbuild} ))
then
  PATH=$( dirname `realpath $0` ):$PATH
  retroarch-build $@
  return $?
fi

if appdir=$( mdfind kMDItemCFBundleIdentifier = $(
  (( ${#zX86} )) &&
    print com.libretro.dist.RetroArchX86 ||
    print com.libretro.dist.RetroArch
) | fzf --select-1 )
then
  $appdir/Contents/MacOS/RetroArch $@
else
  print "None selected." >&2
  exit 1
fi
