#!/usr/bin/env zsh

PATH=${0:A:h}:$PATH
zparseopts -D -E - \
  -x86_64=zX86 \
  -update-cores=zupdate_cores \
  -build=zbuild || exit 1

if (( #zbuild ))
then retroarch-build $@
fi
if ! (( ? )) && (( #zupdate_cores ))
then update-cores
fi
if (( #zbuild + #zupdate_cores ))
then exit $?
fi

if appdir=$( mdfind kMDItemCFBundleIdentifier = $(
  (( #zX86 )) &&
    print com.libretro.dist.RetroArchX86 ||
    print com.libretro.dist.RetroArch
) | fzf --select-1 )
then
  $appdir/Contents/MacOS/RetroArch $@
else
  print "None selected." >&2
  exit 1
fi
