#!/usr/bin/env zsh

zparseopts -D -E - \
  {-arm64,-x86_64}=zarch -metal-hud::=zmetal_hud -build=zbuild \

if (( ${#zbuild} ))
then
  PATH=$( dirname `realpath $0` ):$PATH
  retroarch-build $@
  return $?
fi

aargs=(
  ${zarch:---arm64}
)
if (( ${#zmetal_hud} ))
then
  aargs+=(
    -e MTL_HUD_ENABLED=1
    -e MTL_HUD_CONFIG_FILE=$HOME/.config/metal-hud/${${${zmetal_hud#--metal-hud}#=}:-default}.plist
  )
fi

if (( $( mdfind -count kMDItemCFBundleIdentifier = com.libretro.dist.RetroArch ) > 0 ))
then
  if appdir=$( mdfind kMDItemCFBundleIdentifier = com.libretro.dist.RetroArch | fzf --select-1 )
  then
    arch $aargs $appdir/Contents/MacOS/RetroArch $@
  else
    print "None selected." >&2
    exit 1
  fi
else
  print "RetroArch not found." >&2
  exit 1
fi
