#!/usr/bin/env zsh

initial_mode=56
restore_mode=72

displayplacer "id:1 mode:$initial_mode"
trap 'displayplacer "id:1 mode:$restore_mode"' INT TERM EXIT

log=( ~/Library/Application\ Support/RetroArch/logs/retroarch.log )

tail -fn-1 $log | while read line; do

  if [[ $line =~ "Loading dynamic libretro core from:" ]]; then
    loading=1
  elif [[ $line =~ "Unloading core..." ]]; then
    loading=0
    if `pkill -n rascreen`; then
      print "refresh rate released."
    fi
  fi

  rhz=$( sed -En 's/^\[INFO\] \[Core\] Geometry:.*FPS: ([0-9]+\.[0-9]+).*/\1/p' <<< $line )

  if [[ -n $rhz ]] && (( loading )); then
    # Built-in Liquid Retina XDR Display
    case 1 in
      $(( rhz >= 61.00 ))) hz=120   ;;  # [ >= 61.000 ] VRR
      $(( rhz >= 59.98 ))) hz=60    ;;  # [59.98-60.99] 60.00
      $(( rhz >= 56.94 ))) hz=59.94 ;;  # [56.94-59.97] 59.94
      $(( rhz >= 51.00 ))) hz=120   ;;  # [51.00-56.99] VRR
      $(( rhz >= 49.00 ))) hz=50    ;;  # [49.00-50.99] 50.00
      $(( rhz >= 48.00 ))) hz=48    ;;  # [48.00-48.99] 48.00
      $(( rhz >= 47.95 ))) hz=47.95 ;;  # [47.95-47.99] 47.95
      $(( rhz >= 31.00 ))) hz=120   ;;  # [31.00-47.94] VRR
      $(( rhz >= 30.00 ))) hz=60    ;;  # [30.00-30.99] 30.00 60.00/2
      $(( rhz >= 29.97 ))) hz=59.94 ;;  # [29.97-29.99] 29.97 59.94/2
      $(( rhz >= 26.00 ))) hz=120   ;;  # [26.00-28.96] VRR
      $(( rhz >= 25.00 ))) hz=50    ;;  # [25.00-25.99] 25.00 50.00/2
      $(( rhz >= 24.00 ))) hz=48    ;;  # [24.00-24.99] 24.00 48.00/2
      $(( rhz >= 23.97 ))) hz=47.95 ;;  # [23.97-23.99] 23.97 47.95/2
                        *) hz=0     ;;
    esac
    print "requested: ${rhz}hz"
    rascreen --set-hz $hz &
  fi
done
